spring:
    datasource:
        url: jdbc:mariadb://localhost:3308/dev_db
        username: dev_user
        password: dev_pass
        driver-class-name: org.mariadb.jdbc.Driver
logging:
    level:
        root: DEBUG

message: "This is dev env"