spring:
    datasource:
        url: jdbc:mariadb://localhost:3307/local_db
        username: local_user
        password: local_pass
        driver-class-name: org.mariadb.jdbc.Driver
logging:
    level:
        root: DEBUG